name: Angular Build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - run: |
          echo "Hello World!"
      # Step 2: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo 'Checkout repository successfully'
          npm install            # Install packages
          npm run build          # Build Angular app

      # Step 3: Print build file path
      - name: List dist folder files
        run: ls -R dist/

          
          
          
